<?php
	include('php/wbiims_database.php');
	include('php/head_part.php');
	$role='admin';
	session_start();
	include('php/security.php');
	include('php/hn.php');
	include('php/an.php');
	include('php/aa.php');
	include('php/closing_tags.html');
?>