<?php
	include('php/wbiims_database.php');
	include('php/head_part.php');
	include('php/hn.php');
	$role='oo';
	session_start();
	include('php/security.php');
	include('php/on.php');
	include('php/di.php');
	include('php/closing_tags.html');
?>