<?php
	include('php/wbiims_database.php');
	include('php/head_part.php');
	$role='insured';
	session_start();
	include('php/security.php');
	include('php/hn.php');
	include('php/in.php');
	include('php/reportAccident.php');
	include('php/closing_tags.html');
?>