<?php
	include('php/wbiims_database.php');
	include('php/head_part.php');
	include('php/hn.php');
	$role='cashier';
	session_start();
	include('php/security.php');
	include('php/cn.php');
	include('php/upr.php');
	include('php/closing_tags.html');
?>